-- MySQL Script generated by MySQL Workbench
-- Fri Feb  2 13:38:55 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema HighSchool
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema HighSchool
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `HighSchool` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `HighSchool` ;

-- -----------------------------------------------------
-- Table `HighSchool`.`Class`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `HighSchool`.`Class` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `HighSchool`.`Class` (
  `idClass` INT NOT NULL AUTO_INCREMENT,
  `Class_name` VARCHAR(45) NOT NULL,
  `Class_master` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idClass`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `idClass_UNIQUE` ON `HighSchool`.`Class` (`idClass` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `HighSchool`.`Professor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `HighSchool`.`Professor` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `HighSchool`.`Professor` (
  `idProfessor` INT NOT NULL AUTO_INCREMENT,
  `Professor_name` VARCHAR(45) NOT NULL,
  `School_subject` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idProfessor`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `HighSchool`.`Student`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `HighSchool`.`Student` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `HighSchool`.`Student` (
  `idStudent` INT NOT NULL AUTO_INCREMENT,
  `Student_name` VARCHAR(45) NOT NULL,
  `Class_name` VARCHAR(45) NOT NULL,
  `Student_note` FLOAT NOT NULL,
  `Professor_name` VARCHAR(45) NOT NULL,
  `School_subject` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idStudent`))
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
